#include "Variables.h"

RenderTexture2D GLOBAL_RENDER_TEXTURE{};
int GLOBAL_FONT_SIZE{};
int GLOBAL_TEXT_SPACING{};
Font GLOBAL_FONT{};
SCREENS GLOBAL_CURRENT_SCREEN{};

float GLOBAL_DELAY{};
int GLOBAL_MENU_CURSOR_POS{};
int GLOBAL_OPTIONS_CURSOR_POS{};
int GLOBAL_LANGUAGE_CURSOR_POS{};
int GLOBAL_DIFFICULTY_CURSOR_POS{};
int GLOBAL_STYLE_CURSOR_POS{};
int GLOBAL_BRIGHTNESS_CURSOR_POS{};
int GLOBAL_SOUND_CURSOR_POS{};
int GLOBAL_MUSIC_CURSOR_POS{};
int GLOBAL_PAUSE_CURSOR_POS{};

Vector2 GLOBAL_HERO_POS{};
Vector2 GLOBAL_HERO_MOVE{};
Vector2 GLOBAL_HERO_VELOCITY{};
float GLOBAL_HERO_ROTATION{};

Color TEXTURE_PRO_COLOR()
{
    unsigned char a = GLOBAL_BRIGHTNESS_CURSOR_POS * 255 / 100;
    return {255, 255, 255, a};
}


