#include "Variables.h"

RenderTexture2D GLOBAL_RENDER_TEXTURE{};
int GLOBAL_FONT_SIZE{};
int GLOBAL_TEXT_SPACING{};
Font GLOBAL_FONT{};

int GLOBAL_RENDER_WIDTH{};
int GLOBAL_RENDER_HEIGHT{};
float GLOBAL_SCALE_X{};

SCREENS GLOBAL_CURRENT_SCREEN{};

bool GLOBAL_PAUSE{};
float GLOBAL_DELAY{};
int GLOBAL_MENU_CURSOR_POS{};
int GLOBAL_OPTIONS_CURSOR_POS{};
int GLOBAL_LANGUAGE_CURSOR_POS{};
int GLOBAL_DIFFICULTY_CURSOR_POS{};
int GLOBAL_STYLE_CURSOR_POS{};
int GLOBAL_BRIGHTNESS_CURSOR_POS{};
int GLOBAL_SOUND_CURSOR_POS{};
int GLOBAL_MUSIC_CURSOR_POS{};
int GLOBAL_PAUSE_CURSOR_POS{};

double GLOBAL_HERO_PREVIOUS_TIME{};
float GLOBAL_HERO_RADIUS{};
Vector2 GLOBAL_HERO_POS{};
Vector2 GLOBAL_HERO_MOVE{};
Vector2 GLOBAL_HERO_VELOCITY{};
float GLOBAL_HERO_ROTATION{};

double GLOBAL_GRAVITY_DELAY{};
bool GLOBAL_START_STICK{};

//Clic saut
double GLOBAL_JUMP_CLICK_START_TIME{};
bool GLOBAL_JUMP_IS_PRESSED{};
bool GLOBAL_JUMP_IS_RELEASED{};
double GLOBAL_JUMP_MAX_TIME{}; // Durée max de saut en seconde

//
Color TEXTURE_PRO_COLOR()
{
    unsigned char a = GLOBAL_BRIGHTNESS_CURSOR_POS * 255 / 100;
    return {255, 255, 255, a};
}


Texture2D texture = LoadTexture("assets/moss.png");